### ISSUE TITLE
Can't call commit when autocommit=true

### ISSUE THREAD

**Issue by BlackBeltPanda** [Rsl1122/Plan-PlayerAnalytics#12]
Each time Plan is started or reloaded, it throws this error: http://pastebin.com/raw/cnsQJNkJ

**Comment by Rsl1122** [comment]
`WARN java.sql.SQLException: Can't call commit when autocommit=true
...
WARN at com.djrapitops.plan.database.databases.SQLDB.saveLocationList(SQLDB.java:839)
...
WARN at com.djrapitops.plan.data.cache.DataCacheHandler$2.run(DataCacheHandler.java:203)
...`
Don't worry this is just for me to remember where it happens :)

I'll try to sort this error in the next version. :)

**Comment by Rsl1122** [comment]
Might have been fixed in commit ded1ef53bf63ed5a7987162ee2d081243cc7e670
I still have some features I need to implement before 2.6.0 is released though, but it'll be included in that one.
Just close this issue and open it again if it is still present after 2.6.0
(you can only re-open your own issues if you closed them yourself)
