### ISSUE TITLE
Option to hide gamemode graph.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#160]
Plan v3.5 release build.

There is an option to disable ```GamemodeChangeListener: false``` but not the actual gamemode tracking. Would it be possible to add an option to disable the gamemode tracking and usage graph entirely?

**Comment by Rsl1122** [comment]
Removal of the graph from the html page can be done using [Html Customization](https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/documentation/HtmlCustomization.md)

Disabling features is not the priority, because all additional config settings will add more complexity to the plugin, which means it takes more energy to maintain, test, etc.

**Comment by mibby** [comment]
But wouldn't allowing for the listener to be disabled improve performance on a micro level? Since disabling the listener for gamemode change is kind of pointless when the gamemode itself is still listened for.

**Comment by Rsl1122** [comment]
It's the player join/leave & refresh that keeps the game mode up to date. 
Login & Logout info contains Game mode info as well, disabling this would most likely affect on the scale of 1-10 ms, when the database fetch takes ~50ms anyway. 
It might even nullify the speedup because of the config check addition.
