### ISSUE TITLE
Improve Extremely Large Database operations (Import, Backup, Restore, Move)

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#220]
### Current Import Baseline Benchmarks (3.6.0):
High End: 5 minutes / 35000 players | SSD 
Low End: 67 minutes / 35000 players | HDD, Slow

Command Used: _/plan m import offline_

**Comment by Rsl1122** [comment]
Required for #192

**Comment by Fuzzlemann** [comment]
# Benchmarks for High End with improvements of #216 and #226:

SQLite is not testable because Connection#commit() is still missing

### Testing Environment
**CPU:** Intel Core i7 6700k @ 4.25 GHz
**SSD:** SanDisk SDSSDA120G
**Network Connection Speed (Download; Upload):** 27.55 Mbit/s; 7.98 Mbit/s
**Server Version:** PaperSpigot 1.12-1169 
**Plugins on the Server:** Only Plan
**Plan Version:** Latest Version on my repository (https://github.com/Fuzzlemann/Plan-PlayerAnalytics)
**Plan Debug:** Enabled

### General Information
**MariaDB Server Network Connection Speed  (Download; Upload):** 791.84 Mbit/s; 141.33 Mbit/s
**MariaDB Version:** Ver 15.1 Distrib 10.0.30-MariaDB, for debian-linux-gnu (x86_64)
**Database Collation:** latin1_swedish_ci
**Imported Players:** 60.564

### Testing Procedere

1. Change the constant BATCH_SIZE to the tested batch size
2. Clear the database
3. Start the server
4. Wait for the server to complete startup
5. Execute this command in the console: "plan m import offline -a"
6. Wait for the import to complete
7. Note the result
8. Restart

### 1st Run

**Batch Size - 81536:** 36325 ms
**Batch Size - 40768:** 44907 ms
**Batch Size - 20384:** 36521 ms
**Batch Size - 10192:**  48658 ms
**Batch Size - 5096:** 46273 ms
**Batch Size - 2048 (CURRENT):** 50013 ms
**Batch Size - 1024:** 57752 ms 
**Batch Size - 512:**  54806 ms
**Batch Size - 256:** 79212 ms

### 2nd Run

**Batch Size - 81536:** 37423 ms 
**Batch Size - 40768:** 35109 ms 
**Batch Size - 20384:** 37606 ms 
**Batch Size - 10192:** 41643 ms 

### Anomalies
The amount of players imported is 60535, the same amount of UserData objects are created, but only 60264 UserData are saved to the Database ("[Plan] [DEBUG] DB-MySQL: Save userdata (multiple) for 60264")

### Notes

1. The time is the 41643 that the Database took to save multiple UserDatas ("[PLAN] [DEBUG] Database: Save multiple Userdata took {time} ms")
2. At a batch size of 81536 every query will be placed into one batch because the batch size is greater than the amount of imported players
3. The second run only inherits specific batch sizes that I wanted to retest
4. Batch Sizes that you want to be (re-)tested can be done; just leave a comment

**Comment by Rsl1122** [comment]
Anomalies:
- Some OfflinePlayer objects may contain invalid UUIDs (Players in Offline mode) 
- Some objects may have a duplicate UUID that is removed during Map collection.

**Comment by Rsl1122** [comment]
### Testing Environment

CPU: Intel Core i5 3450 @ 3.10 GHz
HDD: WDC WD10EZRX-00A8LB0
Server Version: Spigot-1.12
Plugins on the Server: Plan, Genie
Plan Version: 1e68a9ce55bf0d06a6256cb461a0b402467b8aca
Plan Debug: Enabled

### General Information

SQLite provided in Spigot.jar
Imported Players: 60.564

### Testing Procedere

Same as above

### 1st Run

**UserData creation (HDD Bottleneck):**
First run: Creating 60535 new UserData objects took 470701 ms
Rest of the runs: Creating 60535 new UserData objects took ~10432 ms

Database save times:
Batch Size - **20384**: 17014 ms
Batch Size - **10192**: 16917 ms
Batch Size - **5096**:  19562 ms
Batch Size - **2048 (CURRENT)**: 18822 ms
Batch Size - **1024**: 18158 ms

### Notes

The time is the time that the Database took to save multiple UserDatas ("[PLAN] [DEBUG] Database: Save multiple Userdata took {time} ms")
Not all batch sizes were tested.

**Comment by Rsl1122** [comment]
Default Batch Size changed to **10192**

**Comment by Rsl1122** [comment]
PreparedStatement fetch size improves performance significantly.
