### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by Fargus5** [Rsl1122/Plan-PlayerAnalytics#335]
Dear

Please take a look into this list of errors that I rencountered:

1) When I’m on the player list it shows to me who is active and who is inactive. This is totally random. For example at now, there is only one user online, and it shows 5 active players… don’t make sense.

If I enter into my profile, or any other it says to me strange informations like:

Oct 02 2017, 20:04 | Changed Name | Fargus5 Fargus5
-- | -- | --
Oct 01 2017, 22:32 | Changed Name | Fargus5 Fargus5
Oct 01 2017, 21:56 | Changed Name | Fargus5 Fargus5
Oct 01 2017, 21:54 | First Logout | Messages sent: 0
Oct 01 2017, 21:54 | First Logout | Messages sent: 0
Oct 01 2017, 21:54 | First Logout | Messages sent: 0
Oct 01 2017, 21:54 | First Logout | Messages sent: 0
Oct 01 2017, 21:54 | First Logout | Messages sent: 0
Oct 01 2017, 21:40 | First Session | Online: 2 Players

But I didn’t change my name. and first logout showed 5 times…

I’ve not got time to take other things, but it’s very bugged…

But I still like your plugin, I want to use, hoping that u will fix all of this and all of next errors… thare are also many errors with advanced achievements…

**Comment by Fargus5** [comment]
What do u mean with " is in the Active slice on the Sessions Tab, Playerbase pie." I don't understand what it is...

and could u try to make it autoupdate instantly?

**Comment by Rsl1122** [comment]
![Example](http://puu.sh/xPWHd/a6e13ec5a3.png)

**Comment by Fargus5** [comment]
Yes, I can see it by myself... what it means?

**Comment by Rsl1122** [comment]
Activity is calculated with the last login of players, how long they have been online, and how many times they have logged in.
If they have logged in just once, activity can not be determined, and thus the player is put to the Unknown part. This part grows if many players join and never return.
If a player has logged in 3 times, and has played in the last 2 weeks, they are considered active. Otherwise they are deemed inactive.
