### ISSUE TITLE
serverName unrecognized in player.html

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#337]
Spigot 1.12.2
PLAN 4.0.1 SQLite

Custom player.html
```
        <h2>${serverName} | ${playerName}</h2>
```

![untitled](https://user-images.githubusercontent.com/17748923/31186012-4f04678a-a8e2-11e7-9114-51f350e83d4b.png)

**Comment by Rsl1122** [comment]
This is due to Bungee functionality, serverName would be determined by the server performing the inspect request.
I can add a networkName though (will be replaced with the same name as serverName would on standalone bukkit servers)

**Comment by SlimeDog** [comment]
I don't understand. I run a standalone Bukkit/Spigot server. ${serverName} works fine in custom server.html. Both files are located on the same server.

**Comment by Rsl1122** [comment]
On Bungee the Inspect page parsing request (Replacing and calculating the placeholder values) is sent to one of the Bukkit servers for processing.
This would mean that a serverName variable would change depending on which server processed the request. - That's why I replaced the original placeholder with just "Player" in the first place.

But yeah networkName should solve that.
