### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by takerukoushirou** [Rsl1122/Plan-PlayerAnalytics#356]
I am using Plan in a reverse proxy configuration using Apache 2 as follows:
- Plan is only bound to localhost using HTTP only;
- a sub-directory of my domain is configured for proxy-pass and proxy-pass-reverse to map requests to the locally bound Plan server;
- Apache is configured for TLS and redirects non-HTTPS requests automatically to HTTPS.

The setup basically works fine and integrates Plan nicely into the domain hierarchy. One problem arises though: As Plan doesn't know it's used in a reverse proxy configuration, generated links in the web UI do not respect the sub-directory and are relative to the TLD.

I was able to get links generated by `/plan inspect` to use the subdirectory by adding it to the configured domain of the `Link` option in the `AlternativeIP` group. (Generated links are still HTTP-only but that is covered by the configured redirection in Apache.)

An idea may be to either use the `Link` option also for links generated by the web UI, or generally add an option for a base URL to be used for all links generated, by commands and the web UI. This base URL could also optionally already contain a protocol that should be used by generated links (e.g. to create HTTPS-only links, independent of any certificate configuration).

**Comment by Rsl1122** [comment]
Protocol given by the commands uses whichever mode (HTTP or HTTPS) the WebServer on the plugin is running.   
Changing the protocol of the link via a config setting would affect systems using the WebAPI through the webserver. (Bungee-Bukkit server connections)
For example:
- Plan is running in HTTPS-mode on ip xx.xx.xx.xx:8804
- Hypothetical config setting is set as http://
- Link therefore use `http://xx.xx.xx.xx:8804`
- PlanBungee reads connection information from MySQL (the link above) and attempts to use HTTP specific connection provider (Due to link starting with http) -> Exception is thrown due to non-relaxed SSL context that doesn't accept ips -> connection fails.

Links on the pages should be using relative URL (../player/PlayerName for example) - if that is not the case for a link please specify where.

Connection safety: Client -HTTPS- Proxy -HTTP- Plan WebServer
For the commands to give links with `https://` in front [Set-Up SSL Certificate](https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up)

**Comment by takerukoushirou** [comment]
Thank you for the insight on the WebAPI and Bungee (I have no experience with either). In that case it will be easier to simply keep the auto-redirect or create an internal certificate for the proxy connection and configure Plan for TLS.

I looked at the player listing URLs and they're indeed relative. The actual problem is, that the URL for the server statistics in use was `/statistics/server`. A relative URL `../player/x` then translates to `/player/x` as `/server` is not interpreted as a directory. Explicitly adding a final slash solves that issue, I'll probably add an implicit redirect for that to the Apache configuration as a quick fix then.

I just tried `/plan network` and it gave me the URL ending in `/statistics/network`, for which the player links then also lead to a one level too high parent directory. 

The command `/plan analyze` though yields `/statistics/server/<ServerName>`, for which the player links are the same and thus correctly lead to a sibling directory.

**Comment by Rsl1122** [comment]
Ah I'll have to add a / to the end of server and network links then, I didn't realize it would do that (since with root addresses it works as intended) :)

**Comment by takerukoushirou** [comment]
This is sadly a side-effect of relative addresses and can sometimes be pretty tricky. For root addresses it doesn't matter as going up further will still yield the root path.

I do not know if there are any other links being generated that link to a virtual sub-directory, the server and network ones are the only ones I encountered so far though :-)

**Comment by Rsl1122** [comment]
Not linked to elsewhere but the command though
