### ISSUE TITLE
Plugin hooks forcefully re-enable and can't be disabled via a reload.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#429]
Plan 4.0.7

Since updating from 4.0.5, I noticed all plugin hooks forcefully re-enabled with the config being reformatted. However, you are no longer able to disable all plugin hooks and then reload in-game via ```/plan reload```. All hooks forcefully re-enable on reload despite the config being uploaded with values set false.

**Comment by mibby** [comment]
Even turning off the server first, then making changes to the config to set all hooks to false, it forcefully re-enables on start-up.

**Comment by Rsl1122** [comment]
Typo in the class handling the sections
```
        ConfigNode pluginSection = section.getConfigNode(pluginName);
        return pluginSection.getChildren().containsKey(dataSource.placeholder);
```
Gets for example config node with "Essentials" then checks for "Essentials.jailed" instead of "Essentials.Data.jailed" -> Returns false -> Method relying on the true/false writes new config section, overriding old values.

### Temporary fix until actual fix is out
copy nodes under PluginName.Data one layer up:

Essentials:
        Enabled: true
        Data:
            jailed: true
            muted: true
            warps: true
        jailed: true
        muted: true
        warps: true
