### ISSUE TITLE
Players page - Negative playtime

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#488]
![Screenshot](https://i.imgur.com/UTHi0SL.png)

After accessing the Players page and clicking once in Playtime, the first players listed have a negative playtime. The screenshot was taken from /server/Survival.

First player on the list: (Screenshot taken from /player/name)
![First Player](https://i.imgur.com/V4K5JmE.png)

Using MySQL, running 4 servers over Bungee.
Plan v4.1.4
TacoSpigot 1.10.2

**Comment by Rsl1122** [comment]
**What I've checked so far**

First I thought that it might be the formatter removing months, but that issue was solved quite a while ago.

So next culprit seems to be Session.getLength when the session is active. [[Session.java, line 125](https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/data/container/Session.java#L125)]
It can't be that either because the player is offline.

Cause not found in:
- ShutdownHook saving sessions
- Join or Leave listeners creating and saving sessions
- Insert to database
- Session Constructors

So, it must be  [[Session.java, line 127](https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/data/container/Session.java#L127)], when sessionEnd would be 0 for some reason.

Checked if System.currentTimeMillis would return 0 at any moment - Doesn't happen.

----

I'm unable to locate the cause for the issue and any additional information would help greatly.

If you still have the issue & database (after this long silence, sorry about that), please send me the result of this SQL query:
```
SELECT session_start, session_end FROM plan_sessions 
JOIN plan_users on plan_users.id=plan_sessions.id 
WHERE name='REPLACE_WITH_AFFECTED_USERNAME';
```

**Comment by Rbot48** [comment]
I can't test if it is still occurring right now since I had to disable Plan because of the issue informed here: #499 
But I've got the following when running the SQL query:
```
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0135 sec)

SELECT session_start, session_end
FROM plan_sessions
JOIN plan_users ON plan_users.id = plan_sessions.id
WHERE name =  'REPLACE_WITH_AFFECTED_USERNAME'
LIMIT 0 , 30
```

**Comment by Rsl1122** [comment]
Please replace `REPLACE_WITH_AFFECTED_USERNAME` with a username of an affected user when running the query

**Comment by Rbot48** [comment]
Oops, I am sorry xD
I actually replaced the username, but I ran the query in the old database.

Here's what is displayed for some players with negative playtime:

| session_start  | session_end |
| :---: | :---: |
| 1512574919837 | 1512576425841  |

(Playtime: -2d -1h -3m -45s; Registered: Dec 27 2017, 17:01; Last Seen: Jan 19 2018, 12:42)

| session_start  | session_end |
| :---: | :---: |
| 1512643871683 | 1512644995738 |

(Playtime: -1d -22h -25m -17s; Registered: Dec 31 2017, 01:41; Last Seen: Jan 19 2018, 08:23)

| session_start  | session_end |
| :---: | :---: |
| 1512745520138 | 1512747815537 |

(Playtime: -1d -14h -27m -57s; Registered: Jan 06 2018, 14:19; Last Seen: Jan 11 2018, 13:31)

**Comment by Rsl1122** [comment]
Seems like they're normal dates. 

I don't know why this Where clause didn't come to mind before, 
Could you run this one?

```
SELECT COUNT(*) FROM plan_sessions WHERE session_start > session_end;
```
It should return 0 if it isn't a database issue and otherwise it'll return a bigger number.  This one will narrow down the code to search by a large margin. 

If it isn't 0 could you run this one and send the result (If it's 0 no need to) 

```
SELECT * FROM plan_sessions WHERE session_start > session_end LIMIT 40
```

**Comment by Rbot48** [comment]
The first query returned `COUNT(*) 7910`.
The second one returned this:
![](https://i.imgur.com/xsnaU2F.png)

**Comment by Rsl1122** [comment]
Thanks for the queries, it looks like the negative playtime might be caused by quickly logging in and leaving.

It is probably related to the 8 Async Task processing queue that, for some reason, performs the tasks in a wrong order when the user joins only for a short amount of time.
Easier fix than I thought then (No need to go through everything hitting my head in the wall for hours). :)

**Comment by Rbot48** [comment]
Nice, thank you for the fast responses :)

**Comment by Rsl1122** [comment]
Confirmed caused by faulty processing queue - Old "End Session" processor was unprocessed while the next session had started, resulting in negative playtime on the new session.

4.2.0 should have solved this issue, but I'll make a modification that allows multiple sessions to exist for a single player in the Session Cache to make sure this doesn't occur again in the future.

**Comment by Rbot48** [comment]
Thanks! I'm running 4.2.0 on a new database and haven't had this issue so far.
