### ISSUE TITLE
Performance Graphs

### ISSUE THREAD

**Issue by sgort87** [Rsl1122/Plan-PlayerAnalytics#492]
Half of the data on the performance graph is unreadable unless you disable the higher range inputs. I'd optimally like to see a time-variable multiple-axes graph, but since that's not possible, a time-variable synchronized graph page could be a handy solution. I think 2 combined graphs should do it in most cases, where one graph would have Players, TPS, and CPU, and the other graph would contain RAM, Entities, and Chunks.

For users who have higher player counts or lower entities, etc, maybe a configuration section for setting up the separation of these graphs?

Better yet... maybe we could persuade HighCharts to add time-variable multi-axes functionality?

**Comment by Rsl1122** [comment]
I went to suggest multiple axes & found out that multiple axis for highstocks is apparently supported.
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/3380563-add-dual-y-axis-to-highstock

However upon further experimentation with the jsfiddle (Adding 3rd axis) it appears to make everything quite painful to read:
![1](http://puu.sh/z1zNh/58d8af34c7.png)

Axis order from left to right: MSFT, AAPL, GOOG

After adding some labels it became a bit more readable, but **x-axis space is reduced.**
![2](http://puu.sh/z1A8B/f1b865e95b.png)
This was **the reason in the old version for not having multiple x-axis** (Due to two graphs being next to each other like this: [3.6.0 Graphs](https://puu.sh/wYsu3/a7ac8c6ca0.png))

Now that the graphs take whole width of the page ([4.0.0 Graphs](https://puu.sh/ymO5O/92c968ab11.png)), it is **not an issue any more** and can be implemented on graphs with less elements, but not the one with everything. 

*I'll add my JSFiddle modification here so that I can use them later:* https://jsfiddle.net/jHjZF/13/

**Comment by Rsl1122** [comment]
Result:

![1](http://puu.sh/zkQ6N/9ab6e88b90.png)

_Axis are hidden if series are hidden_

![2](http://puu.sh/zkQ7Q/966f2de065.png)

**Comment by sgort87** [comment]
I love it! And today is my 31st birthday, so thanks for this present! Looking forward to the update! :D

**Comment by Rsl1122** [comment]
Happy birthday! :)
