### ISSUE TITLE
Updated the plugin and it broke css/js (on Exported HTML)

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#527]
I updated the plugin and it broke all the CSS/JS. 
Do I just delete all the HTML files?

![screenshot-2018-2-16 plan server analysis](https://user-images.githubusercontent.com/144046/36310915-6ad0a290-1321-11e8-85c4-bacea9f1f82a.png)

**Comment by Rsl1122** [comment]
Try restarting first.
If that doesn't work try temporarily removing possible html customization files

If this is exported html it is a bug that has been brought up on discord by @StealWonders

I am currently sick and unable to code, so the fix may take a while.

**Comment by FrozenBeard** [comment]
It is exported HTML! You got a ticket number so I can keep track?

**Comment by Rsl1122** [comment]
Since he did not open an issue and I didn't because of being restricted to mobile, this ticket tracks the issue.

**Comment by Rsl1122** [comment]
Possible temporary solution:

Copy the js, css and plugins folders inside Plan.jar/web/ manually (once) to the appropriate folders in the export folder.

There is likely a script missing from export that is causing the issue, and this will get the missing script where it is wanted. Since the script folders aren't cleared on export it should stay intact.
