### ISSUE TITLE
Track afk time and messages sent for each session.

### ISSUE THREAD

**Issue by RedByte1337** [Rsl1122/Plan-PlayerAnalytics#538]
Hi, we're using your plugin on our server and it's really useful to track how active the staff members are and to see who deserves a promotion and who should get demoted for inactivity. 

But recently, some of the staff members just come online and stand afk for 5+ hours. Their player overview will say they were really active and had up to 50 hours of playtime in the last 7 days, while they were afk 80% of that. So maybe there's some way you can add how much time they spent standing afk each session.

I've noticed it tracks how much messages they send in their first session. But I think it should be useful to see how much messages and commands they've issued in each session. This way I can not only see if they were online, but also if they were actually helping players and were active in chat.

**Comment by Rsl1122** [comment]
Afk time is a part of #460 and is being planned.

----

The messages & commands part is a bit more complex since the current implementation for messages in first session are based on Action Table and they do not have any relation to Sessions in the database.
It also brings the "big brother"-aspect that I don't like a bit too close.

My argument against adding number of messages & commands to sessions is that it might turn Important staff ("the management") to look at just numbers as metrics, when most important things are not trackable via numbers (Eg. How well do players perceive the server if another player/staff is interacting with them) - This is very common issue in software companies where time spent coding or lines coded is used as a metric for success instead of taking the time to figure out the quality of their work instead.

**Comment by RedByte1337** [comment]
There's just not a single plugin out atm which tracks the number of messages sent from a player. It doesn't really have to show the content of the messages anyways, just the amount. And I know numbers are not the best way to manage staff, but if I see a Helper is really active, but they have only sent 5 messages in the last week, this means they're just active to play factions on the server but don't really care about helping players.

**Comment by Rsl1122** [comment]
The problem with that approach is that a session would contain inadequate amount of information to come to that conclusion, perhaps there were no players online during that session - Of course this data is currently available, but calculating the connections for every session might be expensive.

I'll consider it if I can get enough information efficiently from the currently available data and help make more informed decisions.
