### ISSUE TITLE
Player UUID was not found in the database.

### ISSUE THREAD

**Issue by UnioDex** [Rsl1122/Plan-PlayerAnalytics#563]
**Description of the issue**
When i go to a unique player page plugin says player can't found. But i'm clicking it from the list:
http://prntscr.com/j4939s

Here the error page:
http://prntscr.com/j493nl

Note: Server is on offline mode.

**Comment by Rsl1122** [comment]
This sometimes occurs when the player has just been registered, does it occur after the player has a second session?

**Comment by UnioDex** [comment]
Yes. Still gives 404 error.

**Comment by Rsl1122** [comment]
Sorry, I've been busy with other bugs - does this still occur?

It is possible that the bukkit server running the inspect page generation was running with a different database. This has been solved in the [latest Dev release](https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.4.0-DEV3)
----

If it still occurs, please go to `/debug` page after attempting to view the player page.
Copy *Errors* and *Debug log* sections to a comment here so that the issue can be debugged further.

If you're using MySQL, please run `SELECT COUNT(*) FROM plan_users;`

**Comment by UnioDex** [comment]
I just installed the plugin again with complete fresh install. I will monitor for 7 days and will tell you if problem still occurs.

**Comment by UnioDex** [comment]
Problem solved.
