### ISSUE TITLE
Plan's GP integration erases PlayerData

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#572]
https://github.com/TechFortress/GriefPrevention/issues/279

That's my issue thread with GriefPrevention about claim blocks getting lost, the end result was that its Plan erasing Player Claim Blocks.

**Comment by Rsl1122** [comment]
Plan is not removing them on purpose (of course), but it seems that some code is executed on Grief prevention that does.

Thanks for bringing the issue to my attention. 

You can disable the integration in Plan config until the issue is fixed (either by a proper API or by the people over at GriefPrevention)
