### ISSUE TITLE
Disabling Plan Entirely

### ISSUE THREAD

**Issue by UnioDex** [Rsl1122/Plan-PlayerAnalytics#594]
Hello, i removed Plan because of MySQL CPU issues. Now update logs says it is solved but i don't want to restart entire bungeecord if it lags again. So, can you make a command to disable plan entirely? Like /planbungee disable or /plan disable

**Comment by Rsl1122** [comment]
I guess.

----

The lag was caused by a shit ton of duplicate entries in the ip table due to another bug that was also fixed (And the duplicate ips will be removed when run)

You can install Plan on a bukkit server first so that the bukkit server runs the ip table cleaning process. (Wait until /plan status doesn't have `DB version 17->18` task present before installing on Bungee)
