### ISSUE TITLE
Option to hook into Essential's AFK status.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#614]
Would it be possible to implement an option to hook into Essential's AFK status for tracking AFK time rather than using an internal one?

**Comment by Rsl1122** [comment]
I don't think it is very viable because Essentials uses a repeating task to define afk status, whereas Plan figures afk time *after* the fact when an event about the player is fired. (World and gamemode times are calculated the same way, it is very accurate)

Is there a reason you would like to have Essentials do it?

**Comment by mibby** [comment]
Just so there is no inconsistent tracking between when someone is and isn't AFK. If Plan is just as accurate, I'll just set both AFK inactivity timers to match each other.

**Comment by Rsl1122** [comment]
I'll add a thing for if someone uses afk command
