### ISSUE TITLE
[4.4.1] Implementation too dependent on Bukkit, breaks some Sponge compatibility

### ISSUE THREAD

**Issue by NickImpact** [Rsl1122/Plan-PlayerAnalytics#653]
The implementation for additional PluginData currently resides itself as what seems to be dependent on the Bukkit platform, rather than the system in place to handle the scenario. If a Sponge server attempts to add its own data, the system will throw CNFEs in respect to the Bukkit based Plan implementation. I assume this would also apply to systems like Bungee, though I'm unsure as it has been quite a while since I've worked with such.

For your convenience, here's the logged error on attempt to add plugin data from the Sponge platform:
https://hastebin.com/fibutazudu.rb

Now, I just recently forked this, and whilst I try to reattempt to figure out how Maven works once more, I'll be working towards getting this system more adaptable for the foreseeable future. Unless you beat me to it, expect a PR soon.

**Comment by NickImpact** [comment]
Just noticed the project organization branch, so looks like someone else is well on the way to that PR concept

**Comment by Rsl1122** [comment]
Thanks for reporting the issue - I've had plugin data additions on hold because of #648, so this would not have come up until I tried adding support for nucleus

project-reorganization will most likely fix this issue and make it less likely that these mistakes happen. 

This issue can be fixed by replacing Plan.getInstance with PlanPlugin.getInstance in HookHandler, so it'll be fixed in the next bug fix patch (I'm aiming for next weekend as deadline).

Unrelated to the bug:
If you'd like to contribute to project-reorganization we're trying to get rid of getInstance() calls and replace them with constructor injections. :)

Send me a Pm on discord if you're interested and I'll create a groupchat.
