### ISSUE TITLE
Missing data in pingGraph

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#692]
Spigot 1.13 latest
Plan 4.4.3-b2 (4.4.4-DEV2)

There is a lot of missing data in this dataset. But other data sets are displayed with equally space timelines. So it appears that _Customization.Display.GapsInGraphData:true_ is not being observed. Is that possible in the ping case?
![untitled](https://user-images.githubusercontent.com/17748923/44382168-c7f5f680-a4c8-11e8-8f00-628dfc208433.png)

**Comment by SlimeDog** [comment]
I'm included to think that ping data are still useful and should be recorded, even when a player is AFK.

**Comment by Rsl1122** [comment]
I haven't done anything to stop ping gathering from AFK players - What I think is happening is spigot actually measures ping from the packets that are used in normal gameplay, so when the player stops, no packets are sent, which leads the ping data to go outside the Plan filter range of 1ms - 4000ms

----

Gap setting is being observed, otherwise those peaks would be connected to the last value.

In order to graph ping data, the dates need to be set to accuracy of a single minute (as each player is added to gathering individually, leading to their averaging result being at a random second)

I'm unsure why the timeline is acting this way, but it might be because you don't have a timescale selected (7d by default, which might not be available if there isn't enough data)

**Comment by SlimeDog** [comment]
OK. Got it (I think). I'm still confused about why Plan (ie., Spigot/MC) reports ping={45-50), while Linux ping and MC client server list popup report 26.

**Comment by SlimeDog** [comment]
I'm still confused about why Plan (ie., Spigot/MC) reports ping={45-50), while Linux ping and MC client server list popup report 26. But that's a separate issue.
