### ISSUE TITLE
No pings recorded?

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#694]
Spigot 1.13 latest
Plan 4.3.3-b2.1

Single player, configured _plan.ignore.afk:true_

No pings were recorded for these sessions. I was testing the Commands.Data.Ping.* timers. The server was restarted at 05:09, so the first session was immediately after restart, the second session well after restart. Insofar as possible, I was moving during both sessions, so no AFK.

How should I proceed with analysis*?
![untitled](https://user-images.githubusercontent.com/17748923/44415027-28665180-a524-11e8-9b16-4b0f8e113607.png)
![untitled](https://user-images.githubusercontent.com/17748923/44415636-d292a900-a525-11e8-9e49-2c707723f415.png)

**Comment by Rsl1122** [comment]
Found the mistake, used `ms()` instead of `ticks()` which pretty much adds a 500x multiper on any delay
```
long startDelay = TimeAmount.SECOND.ms() * (long) Settings.PING_SERVER_ENABLE_DELAY.getNumber();
```
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/cleaning/Plan/src/main/java/com/djrapitops/plan/system/tasks/BukkitTaskSystem.java#L38

----

Set server enable delay to 0 if you want to test the other delay

**Comment by SlimeDog** [comment]
OK, I reduced the configuration values sufficiently to record pings. I'll tune them better after the next update.
