### ISSUE TITLE
Playtime per week

### ISSUE THREAD

**Issue by CaptainVSGames** [Rsl1122/Plan-PlayerAnalytics#736]
### Is your feature request related to a problem? Please describe.
It's not related to a problem. It's just a quality of life thing really.

### Describe the solution you'd like
I was thinking, (I know nothing about plugin development whatsoever), that you should add an option in the plan webpage to view the player with the most playtime from the last 7 days, 30 days, or a specified period of time, etc. This is so that we can give players prizes and etc. I don't know if this is already in there, but all I could find was their play time.

### Describe alternatives you've considered
There are not really any alternatives.

### Additional context
N/A

**Comment by Rsl1122** [comment]
Anything that filters users based on a parameter (like, what groups they are in, how much they have played & others) are currently very expensive to implement in terms of cpu and memory usage.

This is because all html you load from the webserver is prepared on the server - and the browser does not get the underlying data. Implementing filters would increase the work the server needs to do to display (& store) different kinds of pages.

----

Loosely related, after I finish the current technical debt goal, I'll write a reward plugin that uses Plan data for reward conditions. No ETA though.

**Comment by Rsl1122** [comment]
Looks like this one is similar to #940 - It was incorporated into #963

Please follow #963 if you wish to get updates on this feature.
