### ISSUE TITLE
Servers generate same plan uuid

### ISSUE THREAD

**Issue by Grand-Trizmo** [Rsl1122/Plan-PlayerAnalytics#746]
### Server information
plan version 4.4.7
Server 1: ip as in server.properties 0.0.0.0
               port as in server.properties 25567
               servertype/version  Thermos 1614.57 for minecraft 1.7.10
Server 2: ip 0.0.0.0
               port 25567
               servertype Thermos 1614.57 minecraft 1.7.10

Both servers got uuid 50b6fc18-f533-3016-8036-b591b48dbc3c

Maybe should add server time to the generation of uuid to alleviate this issue

**Comment by Rsl1122** [comment]
Since the servers both have the same settings, it makes sense that the seed for the UUID is the same.
Current implementation attempts to make same UUID for servers with same settings by design.

The reason there is a seed is that if someone deletes their Plan, but not database, it will give the same UUID next time they install. Adding generation time to the seed would make this impossible.

On Bukkit `Server#getServerId` is part of the seed. This method attempts to give unique id on different Bukkit servers, but I think it too is based on the server settings - so it returned same value for both servers.

I think adding MOTD setting might work better, although that setting too is the same with default settings.

**Comment by Rsl1122** [comment]
@Techdaan suggested on github:

> Couldn't you use a MAC address of the server

Looks simple enough
```
InetAddress ip = InetAddress.getLocalHost();
NetworkInterface network = NetworkInterface.getByInetAddress(ip);
byte[] mac = network.getHardwareAddress();
```

**Comment by Rsl1122** [comment]
Issue moved to highest priority.

The current implementation causes more pain than what it solves:
- With the introduction of config transfer, servers with same Server UUID update their configs to a bad state (Config of the other server) upon setup

Thus it has been decided that the server UUID generation will be randomized instead of using a seed, reducing the amount of work needing to be done significantly.
