### ISSUE TITLE
Can't compile because of dependencies

### ISSUE THREAD

**Issue by RoboMWM** [Rsl1122/Plan-PlayerAnalytics#764]
I searched briefly and didn't find any, so here I am complaining that I can't build this plugin because it can't resolve dependencies like AAC and etc - and this is just for the PlanPluginBridge.

If you can deploy PlanPluginBridge on a maven repo somewhere (bintray offers for free) and have that remote repo referenced in Plan's pom, that'd help quite a bit.

**Comment by Rsl1122** [comment]
As outlined in the [Project Set-Up](https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Project-Setup), PlanPluginBridge is included in the repository files, and must be installed manually in order to compile Plan.

I'll keep that repo thing in mind.

**Comment by PyvesB** [comment]
Another alternative to Bintray is simply GitHub, you can host Maven repositories on here. Here's a [StackOverflow post](https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github) with some additional information.

**Comment by Rsl1122** [comment]
I went with Bintray since there were some articles that warned against hosting binaries in git repositories as it increases the size of a clone download each time the file is changed - There were also some remedies like telling Git how to deal with such binaries, but it seemed easier to host it in a maven repo.

Deployment went smoothly with `mvn deploy`

Thanks! :)

*Changes are not yet present on the master branch, since they were made on development branch*
