### ISSUE TITLE
Italian locale has not been translated

### ISSUE THREAD

**Issue by AntoLuMeju99** [Rsl1122/Plan-PlayerAnalytics#782]
### Describe the bug

1.st The Italian locale is in english, just the locale_IT_old is in italian. When i put locale: IT and i restart  the server still in english

### Server information

latest plan version , 1.8.8 spigot

### Additional information

**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment]
This is because the file is in English at the moment.
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/resources/locale/locale_IT.txt

If you would like to contribute an italian translation click the edit button on the top right corner of the file and submit a Pull Request after done :)
