### ISSUE TITLE
Configuration automatically updated to match Proxy

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#881]
What does this mean (from the console/log)?
> [07:20:13 INFO]: [Plan] The Config was updated to match one on the Proxy. Reload for changes to take effect.

### Server information
Spigot 1.13.2
Plan 4.5.2-b4

**Comment by Rsl1122** [comment]
This is message sent by the new network-server configuration transfer task.

Since it works based on the config data present in the database, servers that are not running on networks will still see this message.

----

To reduce confusion I'll change the code so that the last modified date is stored in the database instead of the save date, which should stop this message from showing up unless there actually are changes made on the proxy server.

This system can be disabled by setting `Plugin.Configuration.Allow_bungeecord_to_manage_settings: false`

----

How network-server configuration transfer works:

- On BungeeCord servers the server configs are stored in `/plugins/Plan/serverConfiguration`
- If a file is changed when the server is on, the contents of the config file are placed in the database.
- To keep the files up to date, they are also stored on server boot in case the file was modified offline.
- On both servers and on proxy there is a task that checks if there is data in the database with newer date than last modification of the config file. If the db has newer data, the file is updated.
   - Sidenote: Because currently the data stored in database has the date it's saved and not the file modification date, the file is updated unnecessarily.
- To prevent an infinite loop of server-proxy-server-proxy saving the config, the config is only stored in the database if the contents differ

**Comment by SlimeDog** [comment]
Ah. All good. Configuration changed to disable bungee control.
