### ISSUE TITLE
Date Range Sorting for Players Page

### ISSUE THREAD

**Issue by mercurialmusic** [Rsl1122/Plan-PlayerAnalytics#940]
A feature request: on the players page, it would be extremely useful to be able to sort and view playtime by a date range, or otherwise have a way to essentially see who were the most active players on the network within a given date range rather than simply the top playtime of all time. Currently I still have to rely on my old player time tracking plugin, OnTime, to give me playtime rankings for the previous month. This lets us honor/award our top players, and it's a great little bonus.

Related to that, it would also be useful to see time spent AFK in a similar sortable range, notably to be able to see trends in AFK time or what someone's AFK habits have been in the last week/month/whatever instead of having to add up individual session data from the calendar view. 

We've really been enjoying PLAN, though, and love your work. Thank you!

**Comment by Rsl1122** [comment]
Hi, this feature is great in terms of usefulness, but due to certain decisions made in the development, implementing this would be quite resource intensive.

It will likely not be implemented as described, and instead as a search functionality.

This feature is limited by similar qualities as #639 

----

### Limiting factor

Currently analysis is performed on the server side. Adding any kind of filters (Dates / Groups / Playtime) would mean running analysis every time a filter is changed.

----

### What to try for now

/players page displays a configurable amount of players (25000 by default). On this page Activity index is present, which is calculated using last 3 weeks of session data. While not completely what you might be looking for since the value is not linear, it could give at least some insight on who has been active recently.

It is possible to search for `(Very` to find only those with an activity index over 3.5

**Comment by Rsl1122** [comment]
Incorporated into the ticket above.
