### ISSUE TITLE
Bungeecord Support via MySQL?

### ISSUE THREAD

**Issue by Felix5566** [Rsl1122/Plan-PlayerAnalytics#95]
Is the Plugin via MySQL Bungeecord copatible? The statik of all servers on one Site.

**Comment by Rsl1122** [comment]
Short answer: Not fully supported

Long answer:
Bungeecord is built on a different API than Spigot, which means that it does not contain Bukkit's API. Plan uses Bukkit's Listeners, Tasks & Classes, which are not available in a Bungeecord server.
If you're going to run Plan on all of the servers running Spigot/Bukkit in your Bungee network, you should use a MySQL to connect the data together.
Following datapoints are not syncronized between multiple servers:
- When the player Registered
- Is the player banned
- Is the player Opped
- Is the player online
- Any data in cache while a player is online on one server
- Command Usage & Gamemode time data will most likely be inaccurate because of the way it is saved into the database.
- The way Bungeecord handles IP's means that Geolocation and IPs are unavailable to Plan running on a Spigot server connected to a Bungee server.

All configurations using bungee in any way are untested, and can cause temporary data invisibility in situations where a player moves from one server to another while the database is saving the Player's data. (The saved data might not be visible on the other server until the player leaves)  

In order to achieve bungee support, another version of the plugin would have to be written. Maintaining updates on two similar but same purpose plugins would be extremely tedious.
I have zero bungeecord experience, so testing a bungee version is currently not possible.
